name: Docker

on:
  push:
    branches: [ main ]
    paths:
      - 'Go/**'
      - 'Next.js/**'
      - 'WordPress/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [Go, Next.js, WordPress]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ashok8639289986
        password: Reddy@198510

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.component }}
        file: ./${{ matrix.component }}/Dockerfile
        push: true
        tags: ashok8639289986/myapp-${{ matrix.component }}:latest
